[theme]
base = "dark"
primaryColor = "#0FA968"
backgroundColor = "#08160F"
secondaryBackgroundColor = "#10241A"
textColor = "#EAF2EC"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
